music/urls.py
from django.urls import path
from . import views


app_name = 'music'

urlpatterns = [
    path('', views.SongListView.as_view(), name='index'),
    path('<int:pk>', views.SongDetailView.as_view(), name='detail'),
]

news/urls.py
from django.urls import path
from . import views


app_name = 'news'

urlpatterns = [
    path('', views.NewsListView.as_view(), name='list'),
]

advertisements/models.py
from django.db import models

class Advertisement(models.Model):
    positions = (
        ('a', 'A'),
        ('b1', 'B1'),
        ('b2', 'B2'),
        ('c', 'C'),
        ('d1', 'D1'),
        ('d2', 'D2'),
        ('e', 'E'),
    )

    url = models.URLField()
    text = models.TextField()
    image = models.ImageField(upload_to='images/advertisements')
    position = models.CharField(max_length=2, choices=positions)

    def __str__(self):
        return '{}, {}'.format(self.url, self.position)

templates/layouts/advertisement.html
{% load static %}
<div class="row space">
	{% if advertisements.count > 0 %}
		{% for ad in advertisements %}
			<div class="well">
				<p>{{ ad.text }}</p>
				<a href="{{ ad.url }}">
	    			<img class="img-responsive img-thumbnail" src="{{ ad.image.url }}">
	   			</a>
   			</div>
   		{% endfor %}
   	{% endif %}
</div>

templates/layouts/base.html
<!DOCTYPE html>
{% load static %}
<html lang="fa">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="keywords" content="Music,Song,Album,Download,Singer,موسیقی,ترانه,آهنگ,آلبوم,دانلود,خواننده">
	<title>{% block title %}تک موزیک{% endblock %}</title>

    <link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap.min.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap-rtl.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/font-awesome.min.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">
    {% block rechaptcha_api %}{% endblock %}
</head>
<body>
    <div class="container-fluid">
        <nav class="navbar navbar-default">
            <div class="container-fluid">
                <div class="navbar-header">
              	    <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
                		    <span class="sr-only">Toggle navigation</span>
              	 		    <span class="icon-bar"></span>
              			    <span class="icon-bar"></span>
              			    <span class="icon-bar"></span>
            		    </button>
            		    <a class="navbar-brand" href="{% url 'music:index' %}">تک موزیک</a>
	     	        </div>

          		  <div id="navbar" class="navbar-collapse collapse">
                    <ul class="nav navbar-nav">
                        <li {% if home_active %}class="active"{% endif %}>
                            <a href="#">صفحه اصلی</a>
                        </li>
                        <li class="dropdown">
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">ترانه ها <span class="caret"></span></a>
                            <ul class="dropdown-menu">
                                <li><a href="#">تک آهنگ</a></li>
                                <li role="separator" class="divider"></li>
                                <li><a href="#"></a></li>
                                <li role="separator" class="divider"></li>
                                <li><a href="#">کنسرت</a></li>
                            </ul>
                        </li>
                        <li>
                            <a href="#">اخبار موسیقی</a>
                        </li>
                        <li>
                            <a href="#">تبلیغات</a>
                        </li>
                        <li>
                            <a href="#">
                                تماس با ما
                            </a>
                        </li>
                    </ul>

                    <ul class="nav navbar-nav navbar-left">
                        <li>
                            <!-- Search form -->
                            <form class="form-inline md-form form-sm active-pink active-pink-2">
                                <i class="fa fa-search" aria-hidden="true"></i>
                                <input class="form-control form-control-sm ml-3 w-75" type="text" placeholder="Search" aria-label="Search">
                            </form>
                        </li>
                    </ul>
          		  </div>
        	  </div>
        </nav>
    </div>

    <div class="container-fluid container-content" style="margin-top: 0px; min-height: 480px;">
        <div class="row">
            {% if messages %}
                <ul class="messages list-no-style">
                    {% for message in messages %}
                        <li class="text-center {% if message.tags %} alert alert-{{ message.tags }}{% endif %}">
                            {{ message }}
                        </li>
                    {% endfor %}
                </ul>
            {% endif %}

            <!-- LINKS -->
            <div class="col-md-3" style="border: 1px solid #fff; border-radius: 10px; background: #fff;">
                <h4 class="label-info" style="border-radius: 10px; padding: 10px; font-size: 19px;">
                    دسته بندی سایت
                </h4>

                <h5><strong>تک آهنگ</strong></h5>
                <ul>
                    <li><a href="#">فارسی</a></li>
                    <li><a href="#">ترکی</a></li>
                    <li><a href="#">عربی</a></li>
                    <li><a href="#">کردی</a></li>
                    <li><a href="#">لری</a></li>
                </ul>

                <h5><a href="#"><strong>آلبوم ها</strong></a></h5>
                <h5><strong>آهنگ های پیشنهادی</strong></h5>
                <ul>
                    <li><a href="#">شاد</a></li>
                    <li><a href="#">غمگین</a></li>
                    <li><a href="#">بی کلام</a></li>
                </ul>
                <h5><strong>مداحی</strong></h5>
                <ul>
                    <li><a href="#">فارسی</a></li>
                    <li><a href="#">عربی</a></li>
                    <li><a href="#">انگلیسی</a></li>
                </ul>
                <h5><a href="#"><strong>اخبار موسیقی</strong></a></h5>
                <!-- <ul>
                    <li>one</li>
                    <li>twotwotwo</li>
                    <li>three</li>
                </ul> -->
            </div>

            <!-- POSTS -->
            <div class="col-md-6">
                {% block content %}
                {% endblock %}
            </div>

            <!-- ADVERTISEMENTS -->
            <div class="col-md-3" style="border: 1px solid #fff; border-radius: 10px; background: #fff;">
                <h4 class="label-info" style="border-radius: 10px; padding: 10px; font-size: 19px;">
                    آهنگ های جدید
                </h4>
                <ul>
                    {% if latest_songs %}
                        {% for song in latest_songs %}
                            <li><a href="#">دانلود آهنگ {{ song.name }} از {{ song.singer.name }}</a></li>
                        {% endfor %}
                    {% endif %}
                </ul>
            </div>
        </div>
        <div class="push"></div>
    </div>

    <!-- Footer -->
    <footer style="padding-top: 20px; position: relative; bottom: 0; border-top: 1px solid #225378; margin-right: 0px; background-color: lightblue;">
        <div class="container-fluid">
            <div class="row" style="padding-bottom: 10px;">
                <!-- links col -->
                <div class="col-md-3">
                    <ul style="list-style: none; margin-bottom: 0px;">
                        <li style="margin-bottom: 15px;">
                            <a href="#">فیلم</a>
                        </li>
                        <li style="margin-bottom: 15px;">
                            <a href="#">تئاتر</a>
                        </li>
                        <li style="margin-bottom: 15px;">
                            <a href="#">کنسرت</a>
                        </li>
                        <li style="margin-bottom: 15px;">
                            <a href="#">اخبار</a>
                        </li>
                        <li style="margin-bottom: 15px;">
                            <a href="#">بازیابی رمز عبور</a>
                        </li>
                    </ul>
                </div>

                <!-- second col -->
                <div class="col-md-5">
                    <h1 style="margin-top: 0px; margin-bottom: 15px; color: #225378; font-size: 20px; text-transform: uppercase; letter-spacing: 2px;">
                        پاج تیکت
                    </h1>
                    <p class="footer-text" style="text-align: justify;">
                        بزرگترین سامانه خرید بلیت سینما، همایش، تئاتر و کنسرت در جنوب کشور می باشد. تمامی خدمات اين سـامانه، حسب مورد دارای مجوز های لازم از مراجع مربوطه می‌باشد و فعاليت‌های ايـن سايت تابع قوانين و مقررات جمهـوری اسـلامی ايران است.
                    </p>
                </div>
                <div class="col-md-3 col-md-offset-1">
                    <h1 style="margin-top: 0px; margin-bottom: 15px; color: #225378; font-size: 16px; text-transform: uppercase; letter-spacing: 2px;">
                        ما را در شبکه های اجتماعی دنبال کنید
                    </h1>

                    <a href="https://www.facebook.com" style="margin-left: 20px">
                        <i class="fa fa-facebook-square fa-3x social-fb social-space" id="social"></i>
                    </a>
                    <a href="https://www.twitter.com" style="margin-left: 20px">
                        <i class="fa fa-twitter-square fa-3x social-tw social-space" id="social"></i>
                    </a>
                    <a href="https://instagram.com/" style="margin-left: 20px">
                        <i class="fa fa-instagram fa-3x social-ig" id="social"></i>
                    </a>
                    <a href="https://www.telegram.com" style="margin-left: 20px">
                        <i class="fa fa-telegram fa-3x social-tm" id="social"></i>
                    </a>
                </div>
            </div>

            <div class="row" style="padding-bottom: 10px;">
                <div class="col-md-8 col-md-offset-3 footer-text">
                    تمامی حقوق این وب سایت برای پاج تیکت محفوظ می باشد. | 1396 - 1394 © | طراحی وب سایت از پاج
                </div>
            </div>

        </div>
    </footer>

    <!-- Footer END -->
    <script type="text/javascript" src="{% static 'js/jquery.min.js' %}"></script>
    <script type="text/javascript" src="{% static 'js/bootstrap.min.js' %}"></script>

    {% block javascripts %}
    {% endblock %}

</body>
</html>